name: nvh_movie_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.17
  get_it: ^7.2.0
  injectable_generator: ^2.1.3
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  equatable: ^2.0.5
  pin_code_fields: ^7.4.0
  awesome_dialog: ^3.0.2
  sliver_header_delegate: ^0.0.5
  bottom_navy_bar: ^6.0.0
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  video_player: ^2.4.10
  flutter_share: ^2.0.0
  screenshot: ^1.3.0
  flutter_rating_bar: ^4.0.1
  flutter_credit_card: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
